# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Full Path
name: Full Path LLC
logo_path: /android-chrome-256x256.png
logo_alt: "Full Path Logo Image"
email: info@fullpath.io
description: >- # this means to ignore newlines until "baseurl:"
  Site dedicated to transit and transportation technology, with focus on community transit, demand-response transportation, human services transportation, and mobility as healthcare.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fullpath.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  keviniano
locale: en-US
permalink: /blog/:year/:month/:title/

og_image: /android-chrome-256x256.png
author: Kevin Chambers
twitter:
  username: fullpathtransit

defaults:
  # _posts
  -
    scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: false
      related: true

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-mermaid

mermaid:
  src: 'https://unpkg.com/mermaid@7.1.0/dist/mermaid.js'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
